### PR TITLE
added concatenation post

### PR DESCRIPTION
**Pull request by kevin-m-kent**

### CODE REVIEW

**Comment by tylerwmarrs** [comment]
@kevin-m-kent Thank you for the post. I noticed a typo around "This dataset provies Twitter mention". Would you mind fixing it?

Do you know why the Matrix Profile seems so flat? I wonder if running the 0-1 normalization prior is causing problems.

**Comment by kevin-m-kent** [comment]
I think the flatness is something having to do with how the mp algorithm is handling the buffer inf values. That flatness starts right at that first Inf buffer. I haven't been able to figure out a way around it yet.

**Comment by tylerwmarrs** [comment]
That makes sense. I wonder if you should just use compute instead of analyze, avoiding the plots altogether. This way we can avoid confusion with reading the plot. What do you think @vanbenschoten or @frankiecancino?

**Comment by vanbenschoten** [comment]
I agree with Tyler - using compute might make more sense.

**Comment by kevin-m-kent** [comment]
So I tried just doing compute but I run into the same problem with the matrix profile in that case. Seems like the algorithm doesn't work properly when there are Infs or NaN in the series. Any ideas of how to get around this?

**Comment by tylerwmarrs** [comment]
We are suggesting to avoid visualization of the Matrix Profile altogether. In order to do this, you can call compute and discover discords manually instead of using analyze. Does this help clarify?

**Comment by kevin-m-kent** [comment]
I believe I understand that but isn't the profile still incorrect? even if I don't visualize it, the value is constant for 80% of the points - won't that throw off the discord and motif discovery? i guess I don't understand how the motifs and discords would be of any value in that case.

**Comment by tylerwmarrs** [comment]
I spent some time toying around with your notebook. This is an issue with how MPX handles nan/inf values. Please see the attached PDF on how we can resolve this. The larger issue is to properly handle these values in the MPX algorithm. We can hold off on adding this post until that is fixed as stomp is VERY slow compared to MPX.

[global-discords-kevin.pdf](https://github.com/matrix-profile-foundation/matrix-profile-foundation.github.io/files/5004540/global-discords-kevin.pdf)

**Comment by kevin-m-kent** [comment]
ah ok thanks - I see your changes. makes sense, and thank you for your feedback.

**Comment by tylerwmarrs** [comment]
With minimum and maximum normalization, we get more realistic results. Note that I did not use sklearn to do this.

[global-discords-kevin (1).pdf](https://github.com/matrix-profile-foundation/matrix-profile-foundation.github.io/files/5004576/global-discords-kevin.1.pdf)

**Comment by kevin-m-kent** [comment]
I see yeah, looks good. I was mainly just trying to find a convenience function but this is good.

**Comment by vanbenschoten** [comment]
@kevin-m-kent @tylerwmarrs what are your thoughts on this? Is the min/max normalization easy enough to do?

**Comment by tylerwmarrs** [comment]
@vanbenschoten that is not the problem. Mpx handles missing data poorly making the results useless. The stomp implementation handles it properly. Kaveh is working on resolving the issues with mpx.

**Comment by tylerwmarrs** [comment]
@kevin-m-kent long time no chat! We released a preprocess module that should allow you to complete this post. Basically, you would change the concatenation value from nan to zero and pass the concatenated time series through the preprocess add noise function. See below.

https://matrixprofile.docs.matrixprofile.org/api.html#matrixprofile-preprocess-add-noise-to-series

**Comment by kevin-m-kent** [comment]
sweet @tylerwmarrs ! Thank you. I can work on this sometime this weekend or early next week

**Comment by kevin-m-kent** [comment]
So I finally got to working on this but the matrix profile still looks weird and the motifs and discords are uninteresting and seem off. When you have a chance, could you take a look at my updated notebook to see if I'm using that new method properly? Thank you.

**Comment by tylerwmarrs** [comment]
@kevin-m-kent thank you for submitting the updated code. Unfortunately the approach I suggested with the preprocess module does not appear to work for this use case. The alternative is to use the stomp based algorithm that is listed in the first PDF I posted. Once Kaveh finishes the new MPX implementation, you could re-write an updated version. What do you think about this approach?

**Comment by kevin-m-kent** [comment]
I think I can wait until the mpx implementation is done! No worries.

**Pull request closed without merging**
