### PR TITLE
adding Yues meet the team files

### PR DESCRIPTION
**Pull request by frankiecancino**

### CODE REVIEW

**Comment by vanbenschoten** [comment]
@tylerwmarrs @frankiecancino I think the only thing we'd really need here is an introductory paragraph explaining that MPF and UCR are partnering this summer to advance the open-source implementations of Matrix Profile. I think that will provide the context that we're looking for.

I'll add some content around that later today.

**Comment by vanbenschoten** [comment]
Intro paragraph:

_The Matrix Profile Foundation is excited to partner this summer with two UCR researchers who will help expand the quality and functionality of our codebases! Yue Lue and Kaveh Kamgar bring a wealth of valuable experience that will serve the Matrix Profile community well. In this post, learn a little bit more about Yue and her time with MPF!_

**Comment by vanbenschoten** [comment]
@frankiecancino @tylerwmarrs FYI ^

**Comment by frankiecancino** [comment]
I added Andrew's intro in italics to the beginning of the post. Take a look and let me know if we need to change anything else.

**Comment by vanbenschoten** [comment]
Looks good! Can you push and deploy per the site instructions?

**Comment by tylerwmarrs** [comment]
Looks good to me. @frankiecancino are you going to push and deploy via the readme?

**Comment by frankiecancino** [comment]
Yeah, it looks good locally to me too. I'll merge and deploy

**Pull request merged**
